# Generated by Django 4.2.7 on 2025-09-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20250922_1152'),
        ('courses', '0002_fix_quiz_id_fields'),
    ]

    operations = [
    ]
