# Generated by Django 4.2.7 on 2025-09-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lessonprogress_quiz_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('mixed', 'Mixed')], default='text', max_length=20),
        ),
    ]
