# Generated by Django 5.2.9 on 2026-01-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
